buildings:
- A1FD
- A1FF
- A1MD
- A1MF
- A2MFD
- A2MFF
- AGFD
- AGFF
- AGMD
- AGMF
- ATTD
- ATTF
- B1FD
- B1FF
- B1MD
- B1MF
- B2MFD
- B2MFF
- BGFD
- BGFF
- BGMD
- BGMF
- BTTD
- BTTF
file_format: Water_History_{building}_*.csv
consumption_threshold: 20
forecast_days: 3
